export class TelemetryEvents {
  public static readonly IC3_SDK_NOT_FOUND = "ADAPTER_IC3_SDK_NOT_FOUND";
  public static readonly CHAT_TOKEN_NOT_FOUND = "ADAPTER_CHAT_TOKEN_NOT_FOUND";
  public static readonly IC3_SDK_INITIALIZE_STARTED = "ADAPTER_IC3_SDK_INITIALIZE_STARTED";
  public static readonly IC3_SDK_INITIALIZE_SUCCESS = "ADAPTER_IC3_SDK_INITIALIZE_SUCCESS";
  public static readonly IC3_SDK_INITIALIZE_FAILURE = "ADAPTER_IC3_SDK_INITIALIZE_FAILURE";
  public static readonly IC3_SDK_JOIN_CONVERSATION_STARTED = "ADAPTER_IC3_SDK_JOIN_CONVERSATION_STARTED";
  public static readonly IC3_SDK_JOIN_CONVERSATION_SUCCESS = "ADAPTER_IC3_SDK_JOIN_CONVERSATION_SUCCESS";
}